version: '3'

# Define the services/containers to be run
services:
  myapp: #name of your service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forwarding
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      
  database: # name of the service
    image: mongo # specify image to build container from